### ISSUE TITLE
改client.js中内容,热替换无效

### ISSUE THREAD

**Issue by cjz9032** [zhangmq/react-tiny-env#1]
app.js是正常的,但是改client.js 

[HMR] Nothing hot updated.
bundle.js:3 [HMR] App is up to date.
只是我这样么:D

**Comment by zhangmq** [comment]
https://webpack.github.io/docs/hot-module-replacement-with-webpack.html

> webpack/hot/dev-server reloads the entire page after the HMR update fails. If you want to reload the page on your own, you can add webpack/hot/only-dev-server to the entry point instead.

you can change "webpack/hot/only-dev-server" to "webpack/hot/dev-server" in "webpack.config.js"

**Comment by cjz9032** [comment]
it's working now :+1:
